services:
  # Local MongoDB for development
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    
  # Financial News API Backend
  finapp-api:
    build: .
    ports:
      - "8002:8002"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      LOG_LEVEL: "INFO"
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongo_data:
