version: '3.8'

services:
  # Financial News API Backend
  finapp-api:
    build: .
    ports:
      - "8001:8001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - DATABASE_NAME=financial_news
      - WINDMILL_BASE_URL=http://windmill:8000
      - LOG_LEVEL=INFO
    depends_on:
      - mongo
    networks:
      - finapp-network
    restart: unless-stopped

  # MongoDB Database
  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=financial_news
    volumes:
      - mongo_data:/data/db
    networks:
      - finapp-network
    restart: unless-stopped

  # minio
  minio:
    image: minio/minio
    command: server /data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - finapp-network
    restart: unless-stopped

  # PostgreSQL for Windmill
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=windmill
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=windmill
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finapp-network
    restart: unless-stopped

networks:
  finapp-network:
    driver: bridge

volumes:
  mongo_data:
  postgres_data:
